### PR TITLE
Refactor the package name fixes #11

### LINKED ISSUE #11: Refactor the package name.
In the src folder, there is `notescollab` package under the `notescollab` package. That is not the appropriate way.

Artifact name is already in the group name so we have to remove the artifact name from the group name.
i.e - 
```
├── main
│   ├── java
│   │   └── com
│   │       └── notescollab
│   │           └── notescollab
│   │               ├── config
│   │               ├── controller
│   │               ├── entity      
│   │               ├── NotescollabApplication.java
│   │               ├── repository
│   │               └── services
```

solution:
delete the duplicate package name notescollab.
```
├── main
│   ├── java
│   │   └── com
│   │       └── notescollab
│   │               ├── config
│   │               ├── controller
│   │               ├── entity      
│   │               ├── NotescollabApplication.java
│   │               ├── repository
│   │               └── services
```

### PR DESCRIPTION
**Pull request by Jeyabal-B**
*Renamed the file names by removing the duplicate package name "notescollab" 
*This PR fixes #11
Signed off by Jeyabal-B<jeyabal1993@gmail.com>

### CODE REVIEW

**Review by Krishnapro — CHANGES_REQUESTED** [review]
Hey @Jeyabal-B I'm not seen any changes regarding package import. You have only refactor the class name.

You also have to change package import accordingly.

**Comment by Krishnapro** [comment]
It's a good practice to get assigned an issue first before submitting the pull request.  It helps to save time and prevent conflicts.

**Review by Krishnapro — COMMENTED** [review]
@Jeyabal-B If you are not working on this issue let me know.

**Comment by Jeyabal-B** [comment]
Fixed the import statements. This is still a general Java project. Are you planning to convert it to Maven/Gradle project? That would make it a lot easier to work with.

**Comment by Jeyabal-B** [comment]
> It's a good practice to get assigned an issue first before submitting the pull request. It helps to save time and prevent conflicts.

I don't have the access to assign the issues to anyone or myself.

**Review by Krishnapro — APPROVED** [review]
Now It looks good.

**Comment by Krishnapro** [comment]
> Fixed the import statements. This is still a general Java project. Are you planning to convert it to Maven/Gradle project? That would make it a lot easier to work with. Let me know if these changes are good.

It's already a maven project, please check carefully!

**Pull request merged**
