### PR TITLE
feat: handle duplicate users

### PR DESCRIPTION
**Pull request by mennafabio**
This PR resolves the issue #7 by checking in the database if user with given username **and** email already exists in the database. 

smoke tests done: 
- inserted new user into database -> 200 ✅ 
- inserted user with same username but with different email -> 200 ✅ 
- inserted user with same email but with different username  -> 200 ✅ 
- inserted same user into database -> 409 ❌  (as expected)

### CODE REVIEW

**Review by Krishnapro — CHANGES_REQUESTED** [review]
`username` and `emailid` will be unique, As per your changes and test user can create accounts using previously used `username` or `emailid`. 

So please make changes accordingly.

**Comment by mennafabio** [comment]
> `username` and `emailid` will be unique, As per your changes and test user can create accounts using previously used `username` or `emailid`.
> 
> So please make changes accordingly.

@Krishnapro  Changes made accordingly. 

smoke tests done:
- inserted user with same username but with different email -> 409 ❌ (as expected)
- inserted user with same email but with different username -> 409 ❌ (as expected)
- inserted same user into database -> 409 ❌ (as expected)
- inserted new user into database with different email, different username -> 200 ✅

**Review by Krishnapro — APPROVED** [review]
Looks good to me :)

**Review by Krishnapro — APPROVED** [review]
Looks good, It's a great practice to use separate methods for different features. It makes code maintainable.

**Pull request merged**
